<?$this->headTitle($this->title.'Главная.');?>
<h2>Новости</h2>
<?if($this->auth->hasIdentity()
    && ($this->auth->getIdentity()->User->Rights & Application_Model_User::ALLOW_NEWS)){?>
    <a class="new_item" href="/index/new" title="Добавить новость"><span class="new_img hovered"></span>Добавить новость</a>
<?}?>
<?=$this->paginator?>
<?foreach($this->paginator as $item){?>
    <div class="dream_block <?=$item->Visible?'':'hidden'?>" id="dream<?=$item->Id?>">
        <?if($this->auth->hasIdentity()
        && ($this->auth->getIdentity()->User->Rights & Application_Model_User::ALLOW_NEWS)){?>
            <a href="/index/delete/id/<?=$item->Id?>" title="Удалить" class="delete_img hovered"></a>
            <a href="/index/edit/id/<?=$item->Id?>" title="Редактировать" class="edit_img hovered"></a>
            <a href="/index/publish/id/<?=$item->Id?>" title="<?=$item->Visible?'Скрыть':'Опубликовать'?>" class="<?=$item->Visible?'hide_img':'check_img'?> hovered"></a>
        <?}?>
        <a href="#dream<?=$item->Id?>" title="Подробнее" class="more_img hovered"></a>
        <h4><?=$item->Title?></h4>
        <span class="date"><?=date('d.m.Y H:i:s', strtotime($item->Date))?></span><br/>
        <span class="date">Добавил: <strong><?=$item->UserName?></strong></span><br/>
        <?if(!empty($item->Image)){?>
            <img src="/img/news/<?=$item->Image?>" alt="<?=$item->Title?>" title="<?=$item->Title?>"/>
        <?}?>
        <div class="shorten"><?=mb_substr(strip_tags($item->Text),0,500, 'UTF-8')?></div>
        <div class="full">
            <div>
                <div><?=str_replace("\r\n",'<br/>', $item->Text)?></div>
                <a href="/comment/new/type/<?=Application_Model_Comment::TYPE_NEWS?>/id/<?=$item->Id?>" title="Комментировать" class="comment_img hovered popup_link"></a>
                <a href="/comment/new/type/<?=Application_Model_Comment::TYPE_NEWS?>/id/<?=$item->Id?>" title="Цитировать" class="quote_img hovered popup_link"></a>
            </div>
            <?=$this->action('index','comment',null,array('type'=>Application_Model_Comment::TYPE_NEWS,'id'=>$item->Id))?>
        </div>
    </div>
<?}?>
<?=$this->paginator?>

