<?$this->headTitle($this->title.'Изменение статьи. '.$this->item->Title);?>
<h2>Изменение статьи</h2>
<form method="post" action="/articles/save/id/<?=$this->item->Id?>" enctype="multipart/form-data">
    <table class="form">
        <tr>
            <th>Название</th>
            <td><?=$this->formText('Title',$this->item->Title,array('required'=>true));?></td>
        </tr>
        <tr>
            <th>Автор</th>
            <td><?=$this->formText('Author',$this->item->Author,array('required'=>true));?></td>
        </tr>
        <tr>
            <th>Источник</th>
            <td><?=$this->formText('Source',$this->item->Source);?></td>
        </tr>
        <tr>
            <th>Картинка</th>
            <td>
                <?if(!empty($this->item->Image)){?>
                    <img src="/img/articles/<?=$this->item->Image?>" alt="<?=$this->item->Title?>" title="<?=$this->item->Title?>"/>
                <?}?>
                <?=$this->formFile('Image');?>
            </td>
        </tr>
        <tr>
            <th>Описание</th>
            <td><?=$this->formTextarea('Text',$this->item->Text,array('required'=>true));?></td>
        </tr>
        <tr>
            <th>Опубликовать</th>
            <td><?=$this->formCheckbox('Visible',1,array('checked'=>(bool)$this->item->Visible));?></td>
        </tr>
        <tr>
            <td colspan="2"><?=$this->formSubmit('Submit','Сохранить');?></td>
        </tr>
    </table>
</form>