<?$this->headTitle($this->title.'Добавление статьи.');?>
<h2>Добавление статьи</h2>
<form method="post" action="/articles/save" enctype="multipart/form-data">
    <table class="form">
        <tr>
            <th>Название</th>
            <td><?=$this->formText('Title',null,array('required'=>true));?></td>
        </tr>
        <tr>
            <th>Автор</th>
            <td><?=$this->formText('Author',null,array('required'=>true));?></td>
        </tr>
        <tr>
            <th>Источник</th>
            <td><?=$this->formText('Source');?></td>
        </tr>
        <tr>
            <th>Картинка</th>
            <td><?=$this->formFile('Image');?></td>
        </tr>
        <tr>
            <th>Содержание</th>
            <td><?=$this->formTextarea('Text',null,array('required'=>true));?></td>
        </tr>
        <tr>
            <td colspan="2"><?=$this->formSubmit('Submit','Сохранить');?></td>
        </tr>
    </table>
</form>
<strong>Статья появится на сайте после проверки модератором.</strong>