<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="resourse-type" content="document">
    <meta name="document-state" content="dynamic">
    <meta name="revisit-after" content="2 days">
    <meta name="robots" content="ALL">
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    <link rel="stylesheet" href="/css/main.css"/>
    <link rel="stylesheet" media="screen" type="text/css" href="/css/colorpicker.css" />
    <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    <script src="/js/main.js" type="text/javascript"></script>
    <script src="/js/popup.js" type="text/javascript"></script>
    <script type="text/javascript" src="/js/colorpicker.js"></script>
    <?$this->headMeta()->setName('description', $this->meta.strip_tags($this->headTitle()))
        ->setHttpEquiv('description', $this->meta.strip_tags($this->headTitle()))
        ->setName('keywords', $this->meta.strip_tags($this->headTitle()))
        ->setHttpEquiv('keywords', $this->meta.strip_tags($this->headTitle()))?>
    <?=$this->headMeta() ?>
    <?=$this->headTitle();?>
</head>
<body>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-50328942-2', 'auto');
    ga('send', 'pageview');

</script>
<div id="seo_text"><?=$this->seoText?></div>
<?if(isset($this->mp3)){?>
    <audio id="player" autoplay loop>
        <source src="<?=$this->mp3?>" type="audio/mpeg">
        <embed height="50" width="100" src="<?=$this->mp3?>">
    </audio>
<?}?>
<!--<span id="play_pause"></span>-->
<a href="/" title="Домой"><img id="logo" src="/img/logo.png" alt="Домой" title="Домой"/></a>
<div id="wrap">
    <ul id="menu">
        <li><a href="/" title="Домой"><span class="home_img hovered"></span>Главная</a></li>
        <li><a href="/articles" title="Статьи"><span class="articles_img hovered"></span>Статьи</a></li>
        <li><a href="/books" title="Книги"><span class="books_img hovered"></span>Книги</a></li>
        <?if($this->auth->hasIdentity()){?>
            <li><a href="/my-dreams" title="Мои сны"><span class="dreams_img hovered"></span>Мои сны</a></li>
            <li><a href="/dream-map" title="Карта"><span class="map_img hovered"></span>Карта</a></li>
        <?}?>
    </ul>
    <div id="auth">
        <?if(!$this->auth->hasIdentity()){?>
        <form method="post" action="/auth">
            <?=$this->formText('Email',null,array('placeholder'=>'Email','required'=>true))?><br/>
            <?=$this->formPassword('Password',null,array('required'=>true))?><br/>
            <?=$this->formSubmit('Enter', '', array('title'=>'Вход'))?>
            <a class="registration" href='/auth/registration' title="Регистрация"></a>
        </form>
        <?}else{?>
            <span><?=$this->auth->getIdentity()->User->Name?></span>
            <a class="exit" href="/auth/logout" title="Выйти"></a>
        <?}?>
    </div>
    <div id="breadcrumbs">
        <?foreach($this->breadcrumbs as $key=>$node){
            if($key < (count($this->breadcrumbs)-1)){?>
                <a href="<?=$node['href']?>" title="<?=$node['title']?>"><?=$node['title']?></a>&nbsp;>
            <?}else{?>
                <span><?=$node['title']?></span>
            <?}
        }?>
    </div>
    <div id="rtcol">
        <form id="search_form" method="post" action="/search">
            <?=$this->formText('Search',isset($this->search)?strip_tags($this->search):null,array('placeholder'=>'Поиск','required'=>true))?>
            <?=$this->formSubmit('DoSearch', '', array('title'=>'Искать'))?>
        </form>
        <div class="reclama">
            <!--www.people-group.net-->
            <script async src="//ads.people-group.net/171747/2/1/1/" onload="InitAipg_17174700020001(this)"></script>
            <!--www.people-group.net-->
        </div>
    </div>
    <div id="ltcol">
        <?=$this->action('random','articles')?>
        <?=$this->action('random','books')?>
        <div class="reclama">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Мир снов -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:160px;height:600px"
                 data-ad-client="ca-pub-0639118379623380"
                 data-ad-slot="5996116358"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>
    </div>
    <div id="content">
        <?=$this->layout()->content;?>
    </div>
    <div class="clear"></div>
</div>
<?if(isset($this->stats)){?>
    <table class="statistic">
        <tr>
            <th>Просмотров:</th>
            <td><?=$this->stats->getViews();?></td>
        </tr>
        <tr>
            <th>Посетителей:</th>
            <td><?=$this->stats->getUsers();?></td>
        </tr>
        <tr>
            <th>Зарегистрированных:</th>
            <td><?=$this->stats->getRegistered();?></td>
        </tr>
    </table>
<?}?>
</body>
</html>