<?$this->headTitle($this->title.'Результаты поиска. "'.strip_tags($this->search).'"');?>
<h2>Результаты поиска</h2>
<?if(empty($this->news) && empty($this->articles) && empty($this->books)){?>
    <div>Ничего не найдено</div>
<?}?>
<div>Показаны наиболее подходящие материалы.</div>
<?if(!empty($this->news)){?>
    <h3>Новости</h3>
    <?foreach($this->news as $item){?>
        <div class="dream_block <?=$item->Visible?'':'hidden'?>" id="dream<?=$item->Id?>">
            <?if($this->auth->hasIdentity()
                && ($this->auth->getIdentity()->User->Rights & Application_Model_User::ALLOW_NEWS)){?>
                <a href="/index/delete/id/<?=$item->Id?>" title="Удалить" class="delete_img hovered"></a>
                <a href="/index/edit/id/<?=$item->Id?>" title="Редактировать" class="edit_img hovered"></a>
                <a href="/index/publish/id/<?=$item->Id?>" title="<?=$item->Visible?'Скрыть':'Опубликовать'?>" class="<?=$item->Visible?'hide_img':'check_img'?> hovered"></a>
            <?}?>
            <a href="#dream<?=$item->Id?>" title="Подробнее" class="more_img hovered"></a>
            <h4><?=$item->Title?></h4>
            <span class="date"><?=date('d.m.Y H:i:s', strtotime($item->Date))?></span><br/>
            <span class="date">Добавил: <strong><?=$item->UserName?></strong></span><br/>
            <?if(!empty($item->Image)){?>
                <img src="/img/news/<?=$item->Image?>" alt="<?=$item->Title?>" title="<?=$item->Title?>"/>
            <?}?>
            <div class="shorten"><?=mb_substr(strip_tags($item->Text),0,500, 'UTF-8')?></div>
            <div class="full">
                <div>
                    <div><?=str_replace("\r\n",'<br/>', $item->Text)?></div>
                    <a href="/comment/new/type/<?=Application_Model_Comment::TYPE_NEWS?>/id/<?=$item->Id?>" title="Комментировать" class="comment_img hovered popup_link"></a>
                    <a href="/comment/new/type/<?=Application_Model_Comment::TYPE_NEWS?>/id/<?=$item->Id?>" title="Цитировать" class="quote_img hovered popup_link"></a>
                </div>
                <?=$this->action('index','comment',null,array('type'=>Application_Model_Comment::TYPE_NEWS,'id'=>$item->Id))?>
            </div>
        </div>
    <?}?>
<?}?>
<?if(!empty($this->articles)){?>
    <h3>Статьи</h3>
    <?foreach($this->articles as $item){?>
        <div class="dream_block <?=$item->Visible?'':'hidden'?>" id="dream<?=$item->Id?>">
            <?if($this->auth->hasIdentity()
                && ($this->auth->getIdentity()->User->Rights & Application_Model_User::ALLOW_ARTICLES)){?>
                <a href="/articles/delete/id/<?=$item->Id?>" title="Удалить" class="delete_img hovered"></a>
                <a href="/articles/edit/id/<?=$item->Id?>" title="Редактировать" class="edit_img hovered"></a>
                <a href="/articles/publish/id/<?=$item->Id?>" title="<?=$item->Visible?'Скрыть':'Опубликовать'?>" class="<?=$item->Visible?'hide_img':'check_img'?> hovered"></a>
            <?}?>
            <?if(!empty($item->Source)){?>
                <a target="_blank" href="<?=$item->Source?>" title="Источник" class="link_img hovered"></a>
            <?}?>
            <a href="/articles/single/show/<?=$item->Alias?>" title="Подробнее" class="more_img hovered"></a>
            <h4><?=$item->Title?></h4>
            <span class="date"><?=date('d.m.Y H:i:s', strtotime($item->Date))?></span><br/>
            <span class="date">Добавил: <strong><?=$item->UserName?></strong></span><br/>
            <span class="date">Автор: <strong><?=$item->Author?></strong></span><br/>
            <?if(!empty($item->Image)){?>
                <img src="/img/articles/<?=$item->Image?>" alt="<?=$item->Title?>" title="<?=$item->Title?>"/>
            <?}?>
            <div class="shorten"><?=mb_substr(strip_tags($item->Text),0,500, 'UTF-8')?></div>
        </div>
    <?}?>
<?}?>
<?if(!empty($this->books)){?>
    <h3>Книги</h3>
    <?foreach($this->books as $item){?>
        <div class="dream_block <?=$item->Visible?'':'hidden'?>" id="dream<?=$item->Id?>">
            <?if($this->auth->hasIdentity()
                && ($this->auth->getIdentity()->User->Rights & Application_Model_User::ALLOW_BOOKS)){?>
                <a href="/books/delete/id/<?=$item->Id?>" title="Удалить" class="delete_img hovered"></a>
                <a href="/books/edit/id/<?=$item->Id?>" title="Редактировать" class="edit_img hovered"></a>
                <a href="/books/publish/id/<?=$item->Id?>" title="<?=$item->Visible?'Скрыть':'Опубликовать'?>" class="<?=$item->Visible?'hide_img':'check_img'?> hovered"></a>
            <?}?>
            <a target="_blank" href="/book_storage/<?=$item->File?>" title="Скачать" class="download_img hovered"></a>
            <a href="/books/single/show/<?=$item->Alias?>" title="Подробнее" class="more_img hovered"></a>
            <h4><?=$item->Title?></h4>
            <span class="date"><?=date('d.m.Y H:i:s', strtotime($item->Date))?></span><br/>
            <span class="date">Добавил: <strong><?=$item->UserName?></strong></span><br/>
            <span class="date">Автор: <strong><?=$item->Author?></strong></span><br/>
            <?if(!empty($item->Image)){?>
                <img src="/img/books/<?=$item->Image?>" alt="<?=$item->Title?>" title="<?=$item->Title?>"/>
            <?}?>
            <div class="shorten"><?=mb_substr(strip_tags($item->Description),0,500, 'UTF-8')?></div>
        </div>
    <?}?>
<?}?>

